#!/usr/bin/python

# import scipy as sp
# import numpy as np
import h5py
# import time
import sys
# import re


h5in_file_name=sys.argv[1]

h5file_in=h5py.File(h5in_file_name,"r")

h5file_in=h5py.File('0_Fz.h5.feioutput',"r")


disp=h5file_in['/Model/Nodes/Generalized_Displacements']

disp=map(float, disp)
abs_disp=map(abs,disp)

max_disp=max(abs_disp)


print ("%16.8f" %max_disp)