#!/usr/bin/python

import h5py
import sys

h5in_file_name=sys.argv[1]

h5file_in=h5py.File(h5in_file_name,"r")

disp=h5file_in['/Model/Nodes/Generalized_Displacements']

disp=map(float, disp)
abs_disp=map(abs,disp)

max_disp=max(abs_disp)


print ("%16.8f" %max_disp)