#!/bin/bash

fei2hdf5.py $@


# visitlib=$(find / /usr /home -xdev -name visit 2>/dev/null | grep /lib/site-packages/visit | head -n 1)
# visitdir=${visitlib%/site-packages*}

visitdir=/usr/local/visit/2.9.1/linux-x86_64/lib
export LD_LIBRARY_PATH=${visitdir}

essi_mesh_plot.py feicheck*.feioutput


rm visitlog.py
