#!/usr/bin/python

import matplotlib.pyplot as plt 
import numpy as np 
import sys

import os.path


# #############################
import matplotlib.pylab as pylab
params = {'legend.fontsize': 'x-large',
          'figure.figsize': (10, 8),
         'axes.labelsize': 'x-large',
         'axes.titlesize':'x-large',
         'xtick.labelsize':'x-large',
         'ytick.labelsize':'x-large'}
pylab.rcParams.update(params)
# #############################


filename1 = sys.argv[1]

dat1 = np.loadtxt(filename1)

time1 = dat1[:,0]
acc1 = dat1[:,1]


plt.plot(time1, acc1, 'k', linewidth= 3)
# plt.legend()
plt.xlabel(" Time [second] ")
plt.ylabel(" Displacement [m] ")
plt.grid()

filename = os.path.splitext(filename1)[0]

plt.savefig(filename + ".jpg")
plt.show()


