#!/bin/bash


if [ "$1" != "-d" ]; then
  for file_in in $@
  do file_out=${file_in%.*}.eps
    inkscape --without-gui ${file_in} --export-eps=${file_out}
  done
fi


if [ "$1" == "-d" ]; then
	shift
	for file_in in $@
	do file_out=${file_in%.*}.eps
	inkscape --without-gui ${file_in} --export-eps=${file_out}
	done
	rm $@
fi





