#!/bin/bash


if [ "$1" != "-d" ]; then
  for file_in in $@
  do file_out=${file_in%.*}.pdf
    inkscape --without-gui ${file_in} --export-pdf=${file_out}
  done
fi


if [ "$1" == "-d" ]; then
	shift
	for file_in in $@
	do file_out=${file_in%.*}.pdf
	inkscape --without-gui ${file_in} --export-pdf=${file_out}
	done
	rm $@
fi




# while getopts ":d:" opt; do
#   case $opt in
#     d)
# 		echo "-d was triggered, Parameter: $OPTARG" >&2
# 		for file_in in ${OPTARG}
# 		do file_out=${file_in%.*}.pdf
# 		inkscape --without-gui ${file_in} --export-pdf=${file_out}
# 		done
# 		rm ${OPTARG}
#       ;;
#     \?)
#       echo "Invalid option: -$OPTARG" >&2
#       exit 1
#       ;;
#     :)
#       echo "Option -$OPTARG requires an argument." >&2
#       echo "Parameter: $OPTARG"
#       exit 1
#       ;;
#   esac
# done

